/** Lista curada (no las ~195 de la ISO completa) para el filtro de país del
 * buscador de lugares: Latinoamérica y Caribe completos, más los destinos más
 * comunes del resto del mundo. Si falta un país, añadirlo aquí es la única
 * ampliación necesaria — no hay lógica que dependa del tamaño de la lista. */
export interface Country { code: string; name: string; }

export const COUNTRIES: Country[] = [
  { code: 'ec', name: 'Ecuador' },
  { code: 'co', name: 'Colombia' },
  { code: 'pe', name: 'Perú' },
  { code: 've', name: 'Venezuela' },
  { code: 'bo', name: 'Bolivia' },
  { code: 'cl', name: 'Chile' },
  { code: 'ar', name: 'Argentina' },
  { code: 'py', name: 'Paraguay' },
  { code: 'uy', name: 'Uruguay' },
  { code: 'br', name: 'Brasil' },
  { code: 'mx', name: 'México' },
  { code: 'gt', name: 'Guatemala' },
  { code: 'bz', name: 'Belice' },
  { code: 'sv', name: 'El Salvador' },
  { code: 'hn', name: 'Honduras' },
  { code: 'ni', name: 'Nicaragua' },
  { code: 'cr', name: 'Costa Rica' },
  { code: 'pa', name: 'Panamá' },
  { code: 'cu', name: 'Cuba' },
  { code: 'do', name: 'República Dominicana' },
  { code: 'pr', name: 'Puerto Rico' },
  { code: 'us', name: 'Estados Unidos' },
  { code: 'ca', name: 'Canadá' },
  { code: 'es', name: 'España' },
  { code: 'pt', name: 'Portugal' },
  { code: 'fr', name: 'Francia' },
  { code: 'it', name: 'Italia' },
  { code: 'de', name: 'Alemania' },
  { code: 'gb', name: 'Reino Unido' },
  { code: 'ie', name: 'Irlanda' },
  { code: 'nl', name: 'Países Bajos' },
  { code: 'be', name: 'Bélgica' },
  { code: 'ch', name: 'Suiza' },
  { code: 'at', name: 'Austria' },
  { code: 'gr', name: 'Grecia' },
  { code: 'se', name: 'Suecia' },
  { code: 'no', name: 'Noruega' },
  { code: 'dk', name: 'Dinamarca' },
  { code: 'pl', name: 'Polonia' },
  { code: 'tr', name: 'Turquía' },
  { code: 'ru', name: 'Rusia' },
  { code: 'ma', name: 'Marruecos' },
  { code: 'eg', name: 'Egipto' },
  { code: 'za', name: 'Sudáfrica' },
  { code: 'cn', name: 'China' },
  { code: 'jp', name: 'Japón' },
  { code: 'kr', name: 'Corea del Sur' },
  { code: 'in', name: 'India' },
  { code: 'th', name: 'Tailandia' },
  { code: 'vn', name: 'Vietnam' },
  { code: 'ae', name: 'Emiratos Árabes Unidos' },
  { code: 'au', name: 'Australia' },
  { code: 'nz', name: 'Nueva Zelanda' },
].sort((a, b) => a.name.localeCompare(b.name, 'es'));
